baseurl: 'https://gpaul2.github.io/'
title: Geoji's Blog
theme: hugo-theme-cleanwhite
languageCode: en-us
disqusShortname: 'www-geoji-paul-com'
googleAnalytics: 'G-NBEYQ6NM81'
preserveTaxonomyNames: true
paginate: 5
hasCJKLanguage: true
outputs:
  home:
    - HTML
    - RSS
params:
  header_image: img/defender.jpg
  SEOTitle: Geoji's Blog
  description: 'This is a Blog--- edit later'
  keyword: >-
    security, geoji, blog, leadership, technology
  slogan: Hi, I'm Geoji. I love learning technology and cyber security. This blog is a collection of technology, security and leadership thoughts. Views are mine.
  image_404: img/404-bg.jpg
  title_404: 'Under Construction:('
  omit_categories: false
  page_view_conter: false
  leancloud_app_id: ''
  leancloud_app_key: ''
  sidebar_about_description: 'Christian, Husband, Father, Security, Leader'
  sidebar_avatar: img/GeojiHeadShot.jpg
  featured_tags: true
  featured_condition_size: 1
  ba_track_id: ''
  disqus_proxy: ''
  disqus_site: ''
  reward: false
  friends: false
  bookmarks: false
  about_me: true
  social:
    rss: true
    linkedin: 'https://www.linkedin.com/in/geojipaul/'
    twitter: 'https://twitter.com/g3oji'
#  addtional_menus:
#    - title: About
#      href: /bio
markup:
  tableOfContents:
    endLevel: 2
    startLevel: 1
  highlight:
    style: dracula
